#!/bin/bash

# Clean up intermediate files generated by masurca

sample=$1

indir=masurca/${sample}

rm -rf $indir/work1
rm -f $indir/k_u_hash_0

for f in $indir/*.*; do
	echo $f
	if [[ $f != *"/assemble.sh" ]]; then
		rm -f $f
	fi
done

rm -rf $indir/CA/*.*
rm -rf $indir/CA/{0-*,1-*,4-*,5-*,7-*,8-*}
rm -rf $indir/CA/ovlStoreBackup
rm -rf $indir/CA/runCA-logs
rm -rf $indir/CA/unitig_mers

